version: "3"

services:
  ha-proxy:
    image: haproxy:local
    container_name: haproxy
    restart: always
    ports:
      - 3128:3128
      - 4128:4128
      - 4129:4129
  warp1:
    image: warp:test
    container_name: warp1
    restart: always
    depends_on:
      - ha-proxy
  warp2:
    image: warp:test
    container_name: warp2
    restart: always
    depends_on:
      - ha-proxy
  # warp-tb:
  #   image: warp:test
  #   container_name: warp-tb
  #   restart: always
  #   ports:
  #     - 3129:3128
  #   depends_on:
  #     - ha-proxy
  sshtun1:
    image: sshtun:test
    container_name: sshtun1
    volumes: 
      - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    environment:
      - proxy_user=leo
      - proxy_pass=buceta1
      - SOCKS5_SERVER=pproxy
      - SOCKS5_SERVER_PORT=8080
    depends_on:
      - ha-proxy
      - pproxy0

  sshtun2:
    image: sshtun:test
    container_name: sshtun2
    volumes: 
      - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    environment:
      - proxy_user=leo
      - proxy_pass=buceta1
      - SOCKS5_SERVER=pproxy
      - SOCKS5_SERVER_PORT=8081
    depends_on:
      - ha-proxy
      - pproxy1

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
      
  pproxy0:
    image: pproxy:test
    container_name: pproxy0
    restart: always
    #entrypoint: ["/bin/sleep","50000000000"]
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    environment:
      - SOCKS5_SERVER=haproxy
      - SOCKS5_SERVER_PORT=3128
    depends_on:
      - ha-proxy

  pproxy1:
    image: pproxy:test
    container_name: pproxy1
    restart: always
    #entrypoint: ["/bin/sleep","50000000000"]
    tty: true
    stdin_open: true
    ports:
      - 8081:8080
    environment:
      - SOCKS5_SERVER=torproxy
      - SOCKS5_SERVER_PORT=9050
    depends_on:
      - torproxy

  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do echo 'sleeping to restart warp1' ; sleep 43200; docker restart warp1; echo 'sleeping to restart warp2' ;sleep 43200; docker restart warp2; done"]
    restart: unless-stopped
