version: "3"

services:
  ha-proxy:
    image: haproxy:local
    container_name: haproxy
    restart: always
    ports:
      - 3128:3128
      - 4128:4128
      - 4129:4129
    depends_on:
      - warp1
      - warp2
  warp1:
    image: warp:test
    container_name: warp1
    restart: always
  warp2:
    image: warp:test
    container_name: warp2
    restart: always
  warp-tb:
    image: warp:test
    container_name: warp-tb
    restart: always
    ports:
      - 3129:3128
  sshtun:
    image: sshtun:test
    container_name: sshtun
    volumes: 
      - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    depends_on:
      - ha-proxy
  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
  pproxy:
    image: pproxy:test
    container_name: pproxy
    restart: always
    #entrypoint: ["/bin/sleep","50000000000"]
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do echo 'sleeping to restart warp1' ; sleep 43200; docker restart warp1; echo 'sleeping to restart warp2' ;sleep 43200; docker restart warp2; done"]
    restart: unless-stopped
