version: "3"

services:
  ha-proxy:
    image: haproxy:local
    container_name: haproxy
    restart: always
    ports:
      - 3128:3128
      - 4128:4128
      - 4129:4129
      - 4130:4130
  warp1:
    image: warp:test
    container_name: warp1
    restart: always
    depends_on:
      - ha-proxy
  warp2:
    image: warp:test
    container_name: warp2
    restart: always
    depends_on:
      - ha-proxy
      - sshtun1
      - sshtun2a
      - sshtun2b
  # warp-tb:
  #   image: warp:test
  #   container_name: warp-tb
  #   restart: always
  #   ports:
  #     - 3129:3128
  #   depends_on:
  #     - ha-proxy

  sshtun1:
    #entrypoint: ["/bin/sleep","50000000000"]
    image: sshtun:test
    container_name: sshtun1
    volumes: 
      - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    depends_on:
      - pproxy0
      - torproxy
    environment:
      - SSH_HOST=96.47.227.5
      #- SSH_HOST=186.226.63.15
      - proxy_user=leo
      - proxy_pass=buceta1
      - SOCKS5_SERVER=pproxy0
      - SOCKS5_SERVER_PORT=8080
      - TORPROXY=torproxy
      - TORPROXY_PORT=9050
      - TUNNEL_TIMEOUT=15


  sshtun2a:
    #entrypoint: ["/bin/sleep","50000000000"]
    image: sshtun:test
    container_name: sshtun2a
    volumes: 
      - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    depends_on:
      - pproxy1
      - torproxy
    environment:
      - SSH_HOST=96.47.227.5
      #- SSH_HOST=186.226.63.15
      - proxy_user=leo
      - proxy_pass=buceta1
      - SOCKS5_SERVER=pproxy1
      - SOCKS5_SERVER_PORT=8080
      - TORPROXY=torproxy
      - TORPROXY_PORT=9050
      - TUNNEL_TIMEOUT=15
  sshtun2b:
      #entrypoint: ["/bin/sleep","50000000000"]
      image: sshtun:test
      container_name: sshtun2b
      volumes: 
        - /home/leo/.ssh/id_ed25519:/root/.ssh/id_ed25519
        - /home/leo/.ssh/known_hosts:/root/.ssh/known_hosts
      restart: always
      depends_on:
        - pproxy1
        - torproxy
      environment:
        - SSH_HOST=96.47.227.5
        #- SSH_HOST=186.226.63.15
        - proxy_user=leo
        - proxy_pass=buceta1
        - SOCKS5_SERVER=pproxy1
        - SOCKS5_SERVER_PORT=8080
        - TORPROXY=torproxy
        - TORPROXY_PORT=9050
        - TUNNEL_TIMEOUT=15

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050

  pproxy0:
    image: pproxy:test
    container_name: pproxy0
    restart: always
    #entrypoint: ["/bin/sleep","50000000000"]
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    environment:
      - SOCKS5_SERVER=haproxy
      - SOCKS5_SERVER_PORT=3128
    depends_on:
      - ha-proxy

  pproxy1:
    image: pproxy:test
    container_name: pproxy1
    restart: always
    #entrypoint: ["/bin/sleep","50000000000"]
    tty: true
    stdin_open: true
    ports:
      - 8081:8080
    environment:
      - SOCKS5_SERVER=torproxy
      - SOCKS5_SERVER_PORT=9050
    depends_on:
      - torproxy

  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do echo 'sleeping to restart warp1' ; sleep 43200; docker restart warp1; echo 'sleeping to restart warp2' ;sleep 43200; docker restart warp2; done"]
    restart: unless-stopped
